
FROM maven:3.9.6-eclipse-temurin-17 AS build


WORKDIR /app


COPY pom.xml .
COPY src src


COPY maven-settings-test.xml /usr/share/maven/ref/


RUN apt-get update && apt-get install -y ca-certificates curl


ENV MAVEN_OPTS="-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"

RUN mvn test -Dspring.profiles.active=test



                                   
                                   
